#!/usr/bin/env bash
# action_group.sh - create an Azure Monitor action group and print its resource id
set -euo pipefail

ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found. Please run budget.sh first to generate it."
  exit 1
fi

# Read SUBSCRIPTION_ID from .env
if ! grep -q '^SUBSCRIPTION_ID=' "$ENV_FILE"; then
  echo "Error: SUBSCRIPTION_ID not set in $ENV_FILE"
  exit 1
fi

sub_line=$(grep '^SUBSCRIPTION_ID=' "$ENV_FILE" | tail -n1)
SUBSCRIPTION_ID=${sub_line#SUBSCRIPTION_ID=}
SUBSCRIPTION_ID=${SUBSCRIPTION_ID#\"}
SUBSCRIPTION_ID=${SUBSCRIPTION_ID%\"}

# Read existing BUDGET_NAME if present
BUDGET_NAME=""
if grep -q '^BUDGET_NAME=' "$ENV_FILE"; then
  bn_line=$(grep '^BUDGET_NAME=' "$ENV_FILE" | tail -n1)
  BUDGET_NAME=${bn_line#BUDGET_NAME=}
  BUDGET_NAME=${BUDGET_NAME#\"}
  BUDGET_NAME=${BUDGET_NAME%\"}
fi

# Read existing BUDGET_AMOUNT if present
BUDGET_AMOUNT=""
if grep -q '^BUDGET_AMOUNT=' "$ENV_FILE"; then
  ba_line=$(grep '^BUDGET_AMOUNT=' "$ENV_FILE" | tail -n1)
  BUDGET_AMOUNT=${ba_line#BUDGET_AMOUNT=}
  BUDGET_AMOUNT=${BUDGET_AMOUNT#\"}
  BUDGET_AMOUNT=${BUDGET_AMOUNT%\"}
fi

# Fetch and list available resource groups in the subscription
echo
echo "Fetching resource groups in your active subscription..."
mapfile -t RG_NAMES < <(az group list --query "[].name" -o tsv 2>/dev/null)

if [ ${#RG_NAMES[@]} -eq 0 ]; then
  echo "No existing resource groups found in this subscription."
  read -p "Enter a name to create/use for the new Resource Group: " RG_SELECTED
  RG_SELECTED=$(echo "$RG_SELECTED" | xargs)
else
  echo "Available Resource Groups:"
  echo "---------------------------"
  for i in "${!RG_NAMES[@]}"; do
    idx=$((i+1))
    printf "%3d) %s\n" "$idx" "${RG_NAMES[$i]}"
  done
  echo

  while true; do
    read -p "Select a Resource Group by number (1-${#RG_NAMES[@]}) or enter name manually: " rg_input
    rg_input=$(echo "$rg_input" | xargs)

    if [[ "$rg_input" =~ ^[0-9]+$ ]] && (( rg_input >= 1 && rg_input <= ${#RG_NAMES[@]} )); then
      RG_SELECTED="${RG_NAMES[$((rg_input-1))]}"
      break
    elif [ -n "$rg_input" ]; then
      RG_SELECTED="$rg_input"
      break
    else
      echo "Invalid selection. Please try again."
    fi
  done
fi

if [ -z "$RG_SELECTED" ]; then
  echo "Error: Resource Group name is required to create an Action Group."
  exit 1
fi

echo "Selected Resource Group: $RG_SELECTED"
echo

# Prompt for action group name
read -p "Enter action group name to create: " AG_NAME
AG_NAME=$(echo "$AG_NAME" | xargs)
if [ -z "$AG_NAME" ]; then
  echo "Error: action group name is required."
  exit 1
fi

echo "Creating action group '$AG_NAME' in resource group '$RG_SELECTED'..."

# Create the action group and return its full resource id
if AG_ID=$(az monitor action-group create --name "$AG_NAME" --resource-group "$RG_SELECTED" --query id -o tsv 2>/dev/null); then
  echo "Action group created successfully."
  echo "Resource ID: $AG_ID"

  # Persist parameters and action group id into .env file
  printf "# Generated by action_group.sh on %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$ENV_FILE"
  printf "SUBSCRIPTION_ID=%s\n" "$SUBSCRIPTION_ID" >> "$ENV_FILE"
  if [ -n "$BUDGET_NAME" ]; then
    printf "BUDGET_NAME=%s\n" "$BUDGET_NAME" >> "$ENV_FILE"
  fi
  if [ -n "$BUDGET_AMOUNT" ]; then
    printf "BUDGET_AMOUNT=%s\n" "$BUDGET_AMOUNT" >> "$ENV_FILE"
  fi
  printf "ACTION_GROUP_ID=%s\n" "$AG_ID" >> "$ENV_FILE"
  printf "ACTION_GROUP_RG=%s\n" "$RG_SELECTED" >> "$ENV_FILE"

  echo "Saved subscription action group metadata to $ENV_FILE"
  exit 0
else
  echo "Failed to create action group. Attempting to run command without suppressing output to show error:"
  az monitor action-group create --name "$AG_NAME" --resource-group "$RG_SELECTED"
  exit 1
fi
